//! AI Client trait and implementations
//!
//! Provides a trait-based abstraction for AI backends (embeddings, similarity,
//! semantic bridging), enabling `MockAIClient` for testing without external dependencies.

use async_trait::async_trait;
use quilt_domain::entities::Block;
use thiserror::Error;

/// Errors that can occur when interacting with an AI backend
#[derive(Debug, Error)]
pub enum AIClientError {
    #[error("AI backend error: {0}")]
    Backend(String),
    #[error("AI backend unavailable: {0}")]
    Unavailable(String),
    #[error("embedding dimension mismatch: expected {expected}, got {actual}")]
    DimensionMismatch { expected: usize, actual: usize },
}

/// Configuration for an AI client connection
#[derive(Debug, Clone)]
pub struct AIConfig {
    pub provider: AIProvider,
    pub api_key: Option<String>,
    pub base_url: Option<String>,
    pub model: String,
    /// Expected embedding dimension. If `None`, dimension is inferred from the
    /// first successful embedding call and validated on subsequent calls.
    pub dimension: Option<usize>,
}

impl Default for AIConfig {
    fn default() -> Self {
        Self {
            provider: AIProvider::Mock,
            api_key: None,
            base_url: None,
            model: "mock".to_string(),
            dimension: None,
        }
    }
}

/// Supported AI providers
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AIProvider {
    OpenAI,
    Anthropic,
    Ollama,
    Mock,
}

/// AI Client trait for embedding generation, similarity computation, and concept bridging.
///
/// This trait is object-safe (`dyn AIClient`) and can be implemented by real providers
/// (OpenAI, Anthropic, Ollama) or test doubles (MockAIClient).
#[async_trait]
pub trait AIClient: Send + Sync {
    /// Generate an embedding vector for the given text.
    ///
    /// Returns a vector of f32 values representing the semantic embedding.
    /// The dimensionality is provider-dependent; MockAIClient returns 1536-dimensional vectors.
    async fn embed(&self, text: &str) -> Result<Vec<f32>, AIClientError>;

    /// Compute semantic similarity between two texts.
    ///
    /// Returns a value in [0.0, 1.0], where 1.0 indicates identical content.
    /// The MockAIClient returns 1.0 for identical strings and 0.5 otherwise.
    async fn similarity(&self, a: &str, b: &str) -> Result<f32, AIClientError>;

    /// Generate a synthetic bridge concept connecting two blocks.
    ///
    /// Returns `Some(description)` if a meaningful bridge can be found,
    /// or `None` if the blocks are too dissimilar or the backend is unavailable.
    async fn bridge_concept(&self, a: &Block, b: &Block) -> Result<Option<String>, AIClientError>;

    /// Suggest tags for a block's content.
    ///
    /// Returns a vector of suggested tags based on the content analysis.
    /// The optional context parameter can provide additional context for better suggestions.
    async fn suggest_tags(
        &self,
        _content: &str,
        _context: Option<&str>,
    ) -> Result<Vec<String>, AIClientError> {
        Err(AIClientError::Backend("not implemented".into()))
    }

    /// Suggest links between blocks.
    ///
    /// Returns a vector of block IDs (as strings) that might be relevant links
    /// based on semantic similarity to the given content.
    async fn suggest_links(
        &self,
        _content: &str,
        _existing: &[String],
    ) -> Result<Vec<String>, AIClientError> {
        Err(AIClientError::Backend("not implemented".into()))
    }

    /// Chat completion.
    ///
    /// Returns a string response generated by the AI based on the
    /// system prompt and user prompt.
    async fn chat(
        &self,
        _system_prompt: &str,
        _user_prompt: &str,
    ) -> Result<String, AIClientError> {
        Err(AIClientError::Backend("not implemented".into()))
    }
}

/// Mock AI client for testing — always succeeds with deterministic outputs.
///
/// - `embed` returns a zero-vector of length 1536
/// - `similarity` returns 1.0 for identical strings, 0.5 otherwise
/// - `bridge_concept` always returns `Some("synthetic bridge ...")` describing the pair
#[derive(Debug, Clone, Default)]
pub struct MockAIClient {
    _private: (),
}

impl MockAIClient {
    /// Create a new MockAIClient
    pub fn new() -> Self {
        Self { _private: () }
    }
}

#[async_trait]
impl AIClient for MockAIClient {
    async fn embed(&self, _text: &str) -> Result<Vec<f32>, AIClientError> {
        // Return a fixed 1536-dimensional zero vector (matching OpenAI ada-002 dimension)
        Ok(vec![0.0; 1536])
    }

    async fn similarity(&self, a: &str, b: &str) -> Result<f32, AIClientError> {
        if a == b {
            Ok(1.0)
        } else {
            Ok(0.5)
        }
    }

    async fn bridge_concept(&self, a: &Block, b: &Block) -> Result<Option<String>, AIClientError> {
        Ok(Some(format!(
            "synthetic bridge between '{}' and '{}'",
            a.content.as_plain_text().chars().take(50).collect::<String>(),
            b.content.as_plain_text().chars().take(50).collect::<String>()
        )))
    }

    async fn chat(&self, _system_prompt: &str, user_prompt: &str) -> Result<String, AIClientError> {
        // Return a mock response based on the user prompt
        Ok(format!(
            "Mock response to: {}",
            user_prompt.chars().take(50).collect::<String>()
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use quilt_domain::value_objects::Uuid;
    use std::collections::HashMap;

    fn make_test_block(id: Uuid, content: &str) -> Block {
        Block {
            id,
            page_id: Uuid::new_v4(),
            parent_id: None,
            order: 1.0,
            level: 1,
            format: quilt_domain::value_objects::BlockFormat::Markdown,
            marker: None,
            priority: None,
            content: content.to_string(),
            properties: HashMap::new(),
            refs: Vec::new(),
            tags: Vec::new(),
            scheduled: None,
            deadline: None,
            start_time: None,
            repeated: None,
            logbook: None,
            collapsed: false,
            created_at: chrono::Utc::now(),
            updated_at: chrono::Utc::now(),
            journal_day: None,
            updated_journal_day: None,
        }
    }

    #[tokio::test]
    async fn test_mock_embed_returns_zero_vector() {
        let client = MockAIClient::new();
        let result = client.embed("hello world").await.unwrap();
        assert_eq!(result.len(), 1536);
        assert!(result.iter().all(|&x| x == 0.0));
    }

    #[tokio::test]
    async fn test_mock_embed_empty_string() {
        let client = MockAIClient::new();
        let result = client.embed("").await.unwrap();
        assert_eq!(result.len(), 1536);
    }

    #[tokio::test]
    async fn test_mock_similarity_identical() {
        let client = MockAIClient::new();
        let result = client.similarity("rust", "rust").await.unwrap();
        assert_eq!(result, 1.0);
    }

    #[tokio::test]
    async fn test_mock_similarity_different() {
        let client = MockAIClient::new();
        let result = client.similarity("rust", "golang").await.unwrap();
        assert_eq!(result, 0.5);
    }

    #[tokio::test]
    async fn test_mock_bridge_concept_returns_some() {
        let client = MockAIClient::new();
        let block_a = make_test_block(Uuid::new_v4(), "Concurrency in Rust");
        let block_b = make_test_block(Uuid::new_v4(), "Go channels and goroutines");
        let result = client.bridge_concept(&block_a, &block_b).await.unwrap();
        assert!(result.is_some());
        let bridge = result.unwrap();
        assert!(bridge.contains("synthetic bridge"));
    }

    #[tokio::test]
    async fn test_dyn_trait_object() {
        // Verify MockAIClient can be used as &dyn AIClient
        let client: MockAIClient = MockAIClient::new();
        let _trait_obj: &dyn AIClient = &client;
        // If this compiles, the trait is object-safe
    }
}
