//! BlockSummary entity - LLM-generated summary of a block's content

use crate::value_objects::Uuid;

/// A BlockSummary stores an LLM-generated summary of a block's content,
/// along with a content hash to detect staleness.
#[derive(Debug, Clone, PartialEq)]
pub struct BlockSummary {
    /// The block this summary refers to
    pub block_id: Uuid,
    /// 1-2 sentence summary generated by an LLM
    pub summary: String,
    /// SHA-256 hash of the block content at the time of generation
    pub content_hash: Vec<u8>,
    /// When this summary was generated
    pub generated_at: chrono::DateTime<chrono::Utc>,
}

impl BlockSummary {
    pub fn new(block_id: Uuid, summary: impl Into<String>, content_hash: Vec<u8>) -> Self {
        Self {
            block_id,
            summary: summary.into(),
            content_hash,
            generated_at: chrono::Utc::now(),
        }
    }

    /// Check if this summary is still valid for the given content
    pub fn is_stale(&self, current_hash: &[u8]) -> bool {
        self.content_hash != current_hash
    }
}
