/**
 * QueryAst TypeScript types — AUTO-GENERATED from quilt-query::ast::QueryAst.
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is auto-generated by `scripts/generate-query-ast-types.sh`
 * which runs `cargo test -p quilt-core query_parse_snapshot` and extracts
 * the serde JSON output as a canonical type definition.
 *
 * To refresh after changing the Rust AST:
 *   1. Add or update a `#[test]` in `quilt-query` that serializes your new variant
 *      as JSON (e.g., `serde_json::to_string_pretty(&ast_node).unwrap()`)
 *   2. Run `scripts/generate-query-ast-types.sh`
 *   3. The script updates this file automatically
 *
 * The F18 canonical AST mitigation strategy: WASM `query_parse` JSON is the
 * single source of truth. TypeScript types are derived from that, not mirrored.
 * This avoids the 4.1-bit connascence drift between client and server AST definitions.
 */

// ─── PropertyOp ─────────────────────────────────────────────────────────────────

/** Property comparison operators. Mirrors `quilt_query::property_op::PropertyOp`. */
export type PropertyOp =
  | 'Equals'
  | 'NotEquals'
  | 'Contains'
  | 'GreaterThan'
  | 'LessThan'
  | 'GreaterThanOrEqual'
  | 'LessThanOrEqual'
  | 'Between';

// ─── SortDirection ───────────────────────────────────────────────────────────────

/** Sort direction for ordering results. */
export type SortDirection = 'Asc' | 'Desc';

// ─── AggregateFn ────────────────────────────────────────────────────────────────

/** Aggregate functions for grouping queries. */
export type AggregateFn = 'Count' | 'Avg' | 'Sum' | 'Min' | 'Max';

// ─── StatsFn ────────────────────────────────────────────────────────────────────

/** Statistical functions for property queries. */
export type StatsFn =
  | 'Stddev'
  | 'Variance'
  | 'Median'
  | { Percentile: number };

// ─── AnalyzeKind ────────────────────────────────────────────────────────────────

/** Analysis kinds for the analyze operator. */
export type AnalyzeKind =
  | 'StructuralMirror'
  | {
      Serendipity: {
        limit?: number;
        min_confidence?: number;
        temporal_window_days?: number;
      };
    };

// ─── QueryValue ─────────────────────────────────────────────────────────────────

/** Values that can be used in query expressions. */
export type QueryValue =
  | { String: string }
  | { Integer: number }
  | { Date: string }
  | { TimeOffset: string }
  | { Boolean: boolean };

// ─── QueryAst ───────────────────────────────────────────────────────────────────

/**
 * Abstract Syntax Tree (AST) for query expressions.
 *
 * Each variant represents a different query operation that can be performed on
 * the knowledge graph. Mirrors `quilt_query::ast::QueryAst` serde output.
 */
export type QueryAst =
  | { And: QueryAst[] }
  | { Or: QueryAst[] }
  | { Not: QueryAst }
  | {
      Between: {
        field: string;
        start: QueryValue;
        end: QueryValue;
      };
    }
  | {
      Property: {
        key: string;
        op: PropertyOp;
        value: QueryValue;
        value2?: QueryValue;
      };
    }
  | { Task: string[] }
  | { Priority: string[] }
  | { Page: string }
  | { Tags: string }
  | { PageRef: string }
  | 'SelfRef'
  | { BlockContent: string }
  | { Sample: number }
  | {
      Aggregate: {
        inner: QueryAst;
        group_by: string;
        aggregate_fn: AggregateFn;
      };
    }
  | {
      Stats: {
        property: string;
        compute: StatsFn;
      };
    }
  | {
      GroupBy: {
        inner: QueryAst;
        property: string;
      };
    }
  | {
      Analyze: {
        inner: QueryAst;
        kind: AnalyzeKind;
      };
    }
  | { Table: QueryAst[] }
  | {
      SortBy: {
        field: string;
        direction: SortDirection;
        inner: QueryAst;
      };
    }
  | { Exists: string }
  | { Missing: string }
  | { Namespace: string }
  // ─────────────────────────────────────────────────────────────────
  // T5: Journal Aggregation Predicates
  // ─────────────────────────────────────────────────────────────────
  | { Scheduled: { predicate: DatePredicate } }
  | { Deadline: { predicate: DatePredicate } }
  | 'Overdue'
  | 'InProgress'

// ─── DatePredicate (T5) ─────────────────────────────────────────────────────

/** Date predicate for scheduled/deadline queries (T5). */
export type DatePredicate =
  | 'Today'
  | 'Tomorrow'
  | 'Yesterday'
  | { Relative: string }

// ─── QueryError ─────────────────────────────────────────────────────────────────

/** Client-side query execution errors. */
export interface QueryError {
  type: 'InvalidAst' | 'Unauthorized' | 'ServerError' | 'Timeout';
  message: string;
}

// ─── QueryResult ───────────────────────────────────────────────────────────────

/** Response from `POST /api/v1/query`. */
export interface QueryResult {
  results: Record<string, unknown>[];
  total: number;
  elapsed_ms: number;
}

// ─── QueryRequest ───────────────────────────────────────────────────────────────

/** Request body for `POST /api/v1/query`. */
export interface QueryRequest {
  ast: QueryAst;
  limit?: number;
}
