//! Typed wrapper around the generated `quilt_core` WASM module.
//!
//! The pkg file (`pkg/quilt_core.js`) is generated by `wasm-pack` from
//! the `quilt-core` crate. It exposes JS functions whose signatures
//! mirror the Rust `#[wasm_bindgen]` exports. This module re-exports
//! them with concrete TypeScript types so call sites don't need to use
//! `any`.
//!
//! When new exports are added to the Rust crate, regenerate the pkg
//! with `wasm-pack build` and add the corresponding typed wrappers
//! below.

import initWasmRaw, {
  init as initPanicHook,
  ping,
  get_version,
  get_state,
  load_page,
  dispatch,
  undo,
  redo,
  parse_inline,
  // History-stack bridge (added by the sdd-apply history-bridge task).
  // These exist in the WASM pkg after `wasm-pack build` is run.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} from './pkg/quilt_core.js'
import type { Block, OutlinerCommand } from '@shared/types/api'

// The `quilt_core.js` module has no public type declarations for the
// new history functions yet (the WASM pkg is built from Rust). We
// declare them here so call sites stay type-safe. The runtime values
// come from the same JS module.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const pkg = (initWasmRaw as any).__wasm ?? (initWasmRaw as any)

// ── Lifecycle ─────────────────────────────────────────────────────

/** Initialise the WASM module. Safe to call multiple times. */
export async function loadWasm(): Promise<void> {
  await initWasmRaw()
  initPanicHook()
  if (!ping()) throw new Error('quilt-core WASM ping returned false')
}

export { get_version, ping }

// ── Page state ────────────────────────────────────────────────────

/** Load blocks for a page and stash them in the WASM-side BLOCKS map. */
export function wasmLoadPage(pageId: string, blocks: Block[]): unknown {
  return load_page(pageId, JSON.stringify(blocks))
}

/** Get the WASM-side state snapshot for a page. */
export function wasmGetState(pageId: string): unknown {
  const raw = get_state(pageId)
  return typeof raw === 'string' ? JSON.parse(raw) : raw
}

/** Dispatch a `types::OutlinerCommand` (the WASM boundary, not the history one). */
export function wasmDispatch(pageId: string, command: unknown): unknown {
  const raw = dispatch(
    pageId,
    typeof command === 'string' ? command : JSON.stringify(command),
  )
  return typeof raw === 'string' ? JSON.parse(raw) : raw
}

/** Parse inline content into typed segments. */
export function wasmParseInline(content: string): unknown {
  const raw = parse_inline(content)
  return typeof raw === 'string' ? JSON.parse(raw) : raw
}

// ── History-stack bridge ──────────────────────────────────────────
//
// The functions below come from the Rust `HistoryStack` bridge
// (`crates/quilt-core/src/wasm.rs`). They are intentionally typed as
// `(...args: unknown[]) => unknown` because the pkg's .d.ts is
// regenerated by `wasm-pack build` and the build artefact is not
// re-built on every TypeScript change. The wrappers below translate
// between TypeScript and the pkg's expected call shape.

type WasmExport = (...args: unknown[]) => unknown

// We pull the functions off the module object the same way the
// generated JS would, by name. The pkg's `__wbindgen_export_*` is
// private, so we use a safe fallback: if the named export exists, use
// it; otherwise the function throws at runtime.
function getExport(name: string): WasmExport | undefined {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const mod = (initWasmRaw as any)
  if (typeof mod === 'function') {
    // The default export in some versions is the module itself
    if (name in mod) return mod[name].bind(mod)
  }
  // Named exports are static — try to resolve them at module load.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const all = mod as Record<string, unknown>
  if (name in all) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const fn = (all as any)[name]
    return typeof fn === 'function' ? (fn as WasmExport) : undefined
  }
  return undefined
}

// Throws a clear error if the WASM pkg was not rebuilt with the new
// history exports. After `wasm-pack build`, the imports at the top
// of this file should be extended and these shims can be replaced
// with direct imports.
function requireExport(name: string): WasmExport {
  // Preferred path: the named import from `./pkg/quilt_core.js`.
  // If `wasm-pack build` has been run, the imports above are
  // extended and `pkg[name]` resolves.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const direct = (pkg as any)?.[name]
  if (typeof direct === 'function') return direct as WasmExport
  // Fallback: scan the whole module.
  const fallback = getExport(name)
  if (fallback) return fallback
  throw new Error(
    `WASM export "${name}" not found. Run \`wasm-pack build\` in ` +
      `crates/quilt-core to regenerate pkg/quilt_core.js.`,
  )
}

/** Initialise a history stack. Returns a `u32` id. */
export function wasmHistoryNew(blocks: Block[]): number {
  return requireExport('history_new')(blocks) as number
}

/** Apply a command and return the new block list. */
export function wasmHistoryApply(
  stackId: number,
  command: OutlinerCommand,
): Block[] {
  return requireExport('history_apply')(stackId, command) as Block[]
}

/** Undo the last command. Returns the new block list, or `null`. */
export function wasmHistoryUndo(stackId: number): Block[] | null {
  const out = requireExport('history_undo')(stackId)
  return out == null ? null : (out as Block[])
}

/** Redo the next command. Returns the new block list, or `null`. */
export function wasmHistoryRedo(stackId: number): Block[] | null {
  const out = requireExport('history_redo')(stackId)
  return out == null ? null : (out as Block[])
}

export function wasmHistoryCanUndo(stackId: number): boolean {
  return Boolean(requireExport('history_can_undo')(stackId))
}

export function wasmHistoryCanRedo(stackId: number): boolean {
  return Boolean(requireExport('history_can_redo')(stackId))
}

export function wasmHistoryFree(stackId: number): void {
  requireExport('history_free')(stackId)
}

// ── StrategySelector bridge (roadmap #26) ──────────────────────────
//
// The Rust `DefaultStrategySelector` (crates/quilt-core/src/strategy.rs)
// is exported to WASM as a class `WasmStrategySelector` with a
// `select(block_json)` method that returns the strategy name
// (`"task"`, `"query"`, `"view"`, `"agent-run"`, `"default"`) for the
// given block. The bridge below adapts the JS-friendly `Block`
// shape (array of `BlockProperty` records) into the
// `{"properties": {"type": "..."}}` JSON the WASM function expects.

/**
 * Build the JSON shape the WASM `select()` wants from a JS `Block`.
 *
 * The Rust `strategy::Block` is `{ properties: HashMap<String, String> }`
 * (serialized as `{ "properties": { "k": "v" } }`). The front-end
 * `Block.properties` is an array of `{ key, value, type }` records.
 */
function blockToStrategyJson(block: {
  properties?: Array<{ key: string; value: string | number | boolean | null }>
}): string {
  const props: Record<string, string> = {}
  for (const p of block.properties ?? []) {
    if (!p) continue
    if (p.value == null) continue
    // Coerce non-string values to their string form so boolean /
    // number properties (e.g. `resolved:: true`) don't silently fall
    // through to the default strategy.
    props[p.key] = typeof p.value === 'string' ? p.value : String(p.value)
  }
  return JSON.stringify({ properties: props })
}

/**
 * Pick a strategy for the given block. Returns the strategy name
 * (`"task" | "query" | "view" | "agent-run" | "default"`) or `null`
 * if WASM is not loaded / not built yet.
 *
 * The hook `useBlockStrategy` wraps this with a JS-only fallback
 * (always returns `"default"`) so the rest of the app never breaks
 * when the WASM module is missing.
 */
export function wasmStrategySelect(block: {
  properties?: Array<{ key: string; value: string | number | boolean | null }>
}): string | null {
  const Ctor = requireExport('WasmStrategySelector') as unknown
  // wasm-bindgen generates a JS class; we instantiate with `new` and
  // call `.select(json)` on the instance. The constructor is
  // `with_builtins` (canonical registry) — exposed as the default
  // #[wasm_bindgen(constructor)] on the Rust struct.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const instance = typeof Ctor === 'function' ? new (Ctor as any)() : Ctor
  const json = blockToStrategyJson(block)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const result = (instance as any).select(json)
  if (typeof result === 'string') return result
  return null
}

/** Names of all registered strategies, in registration order. */
export function wasmStrategyAll(): string[] {
  const Ctor = requireExport('WasmStrategySelector') as unknown
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const instance = typeof Ctor === 'function' ? new (Ctor as any)() : Ctor
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const result = (instance as any).all_strategies()
  return Array.isArray(result) ? (result as string[]) : []
}

// ── Projection bridge (ADR-0028) ─────────────────────────────────
//
// The Rust `WasmProjectionResolver` (crates/quilt-core/src/projection/)
// is exported to WASM as `projection_resolve(block_json) -> string`.
// The bridge below adapts the JS-friendly `Block` shape (array of
// `BlockProperty` records) into the `BlockDto` JSON the WASM function
// expects, and coerces the WASM return value into the UI's
// `ProjectionView` shape. The hook `useProjection` wraps this with
// HTTP-fallback; the metrics layer records the success/failure path.

/**
 * Convert a `Block` (with `properties: BlockProperty[]`) to a
 * `BlockDto` JSON string the WASM function expects.
 *
 * The Rust `BlockDto` is a flat object: `{ id, pageId, parentId,
 * content, order, level, marker, priority, collapsed, properties:
 * Record<string, JSON>, refs: string[], createdAt, updatedAt,
 * createdBy }`. The front-end `Block` has a similar shape but
 * `properties` is an array of `{ key, value, type }` records.
 *
 * The conversion drops `pageName` (not in BlockDto), drops `children`
 * (UI-only, not in BlockDto), and converts each `BlockProperty` to
 * a `key: value` entry in a JSON object map. Non-string values
 * (numbers, booleans) are preserved as JSON natives — the WASM
 * predicates use JSON equality, not string equality.
 */
function blockToWasmJson(block: {
  id: string
  pageId: string
  parentId?: string | null
  content: string
  order?: number
  level?: number
  marker?: string | null
  priority?: string | null
  collapsed?: boolean
  properties?: Array<{ key: string; value: string | number | boolean | null }>
  refs?: string[]
  createdAt?: string
  updatedAt?: string
  createdBy?: string | null
}): string {
  const props: Record<string, string | number | boolean | null> = {}
  for (const p of block.properties ?? []) {
    if (!p) continue
    if (p.value == null) continue
    props[p.key] = p.value
  }
  return JSON.stringify({
    id: block.id,
    pageId: block.pageId,
    parentId: block.parentId ?? null,
    content: block.content,
    order: block.order ?? 0,
    level: block.level ?? 1,
    marker: block.marker ?? null,
    priority: block.priority ?? null,
    collapsed: block.collapsed ?? false,
    properties: props,
    refs: block.refs ?? [],
    createdAt: block.createdAt ?? new Date(0).toISOString(),
    updatedAt: block.updatedAt ?? new Date(0).toISOString(),
    createdBy: block.createdBy ?? null,
  })
}

/** Result of a successful WASM projection resolution. */
export interface WasmProjectionResult {
  /** The resolved view (byte-equal to `ProjectionView` minus the
   *  three WASM-specific metadata fields). */
  view: import('@features/projection/types').ProjectionView
  /** Winning contract id (e.g., "task", "default"). */
  contractId: string
  /** True if a tied-score conflict was detected. */
  hadConflict: boolean
}

/**
 * Coerce a single JSON value from the WASM return into the UI's
 * `string | number | boolean | null` contract.
 *
 * - JSON string → string (pass-through; dates are ISO 8601 strings)
 * - JSON number → number
 * - JSON boolean → boolean
 * - JSON null → null
 * - JSON array → joined with ", " (the same coercion `api.getBlockProjection`
 *   applies to array values)
 * - JSON object → JSON.stringify(object) (defensive; the V1 contracts
 *   don't emit object values, but a future V2 contract might)
 */
function coerceValue(v: unknown): string | number | boolean | null {
  if (v == null) return null
  if (typeof v === 'string') return v
  if (typeof v === 'number') return Number.isFinite(v) ? v : null
  if (typeof v === 'boolean') return v
  if (Array.isArray(v)) {
    return v.map(coerceValue).join(', ')
  }
  if (typeof v === 'object') {
    try {
      return JSON.stringify(v)
    } catch {
      return null
    }
  }
  return null
}

/** Coerce a `WasmProjectionView` JSON object into a UI `ProjectionView`. */
function coerceView(raw: Record<string, unknown>): import('@features/projection/types').ProjectionView {
  const decorations = Array.isArray(raw.decorations) ? raw.decorations : []
  const conflicts = Array.isArray(raw.conflicts) ? raw.conflicts : []
  const links = Array.isArray(raw.links) ? raw.links : []
  const children = Array.isArray(raw.children) ? raw.children : []
  const properties = (raw.properties && typeof raw.properties === 'object'
    ? raw.properties
    : {}) as Record<string, unknown>

  return {
    text: typeof raw.text === 'string' ? raw.text : '',
    links: links as import('@features/projection/types').LinkView[],
    children: children.filter((c): c is string => typeof c === 'string'),
    decorations: decorations.map((d) => {
      const dec = d as Record<string, unknown>
      return {
        kind: String(dec.kind ?? 'generic-badge') as import('@features/projection/types').DecorationKind,
        target: typeof dec.target === 'string' ? dec.target : '',
        value: coerceValue(dec.value),
        weight: typeof dec.weight === 'number' ? dec.weight : 0,
      }
    }),
    conflicts: conflicts as import('@features/projection/types').ProjectionConflict[],
    properties: Object.fromEntries(
      Object.entries(properties).map(([k, v]) => [k, coerceValue(v)])
    ) as Record<string, string | number | boolean | null>,
  }
}

/**
 * Resolve a block's projection view via the WASM module.
 *
 * Returns `null` if the WASM module is not loaded OR the
 * `projection_resolve` export is missing. The hook treats `null`
 * as "use HTTP fallback".
 *
 * Returns a `WasmProjectionResult` on success. The `view` is
 * coerced to the UI's `ProjectionView` shape (Date strings,
 * array join, null preservation).
 *
 * Catches all exceptions (TypeError, JSON.parse errors, property
 * access errors) and returns `null` — the caller never has to
 * wrap the call in try/catch.
 */
export function wasmProjectionResolve(block: {
  id: string
  pageId: string
  parentId?: string | null
  content: string
  order?: number
  level?: number
  marker?: string | null
  priority?: string | null
  collapsed?: boolean
  properties?: Array<{ key: string; value: string | number | boolean | null }>
  refs?: string[]
  createdAt?: string
  updatedAt?: string
  createdBy?: string | null
}): WasmProjectionResult | null {
  try {
    const exportFn = getExport('projection_resolve')
    if (!exportFn) return null
    const blockJson = blockToWasmJson(block)
    const raw = exportFn(blockJson)
    // The WASM function returns a string (JSON); parse it.
    const jsonStr = typeof raw === 'string' ? raw : JSON.stringify(raw)
    const parsed = JSON.parse(jsonStr) as Record<string, unknown>
    if (!parsed || typeof parsed !== 'object') return null
    const view = coerceView(parsed)
    const contractId = typeof parsed.wasm_contract_id === 'string'
      ? parsed.wasm_contract_id
      : 'default'
    const hadConflict = parsed.wasm_had_conflict === true
    return { view, contractId, hadConflict }
  } catch {
    // Silent fallback — the hook will use HTTP.
    return null
  }
}

// ── Re-exports for the legacy page-level undo/redo (now no-ops) ───

export const wasmUndo = undo
export const wasmRedo = redo

// Suppress the "unused variable" warning for the `pkg` reference while
// it remains the primary route into the module. Once the imports at
// the top of this file are extended, the line can be removed.
void pkg
