//! Typed wrapper around the generated `quilt_core` WASM module.
//!
//! The pkg file (`pkg/quilt_core.js`) is generated by `wasm-pack` from
//! the `quilt-core` crate. It exposes JS functions whose signatures
//! mirror the Rust `#[wasm_bindgen]` exports. This module re-exports
//! them with concrete TypeScript types so call sites don't need to use
//! `any`.
//!
//! When new exports are added to the Rust crate, regenerate the pkg
//! with `wasm-pack build` and add the corresponding typed wrappers
//! below.

import initWasmRaw, {
  init as initPanicHook,
  ping,
  get_version,
  get_state,
  load_page,
  dispatch,
  undo,
  redo,
  parse_inline,
  // History-stack bridge (added by the sdd-apply history-bridge task).
  // These exist in the WASM pkg after `wasm-pack build` is run.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} from './pkg/quilt_core.js'
import type { Block, OutlinerCommand } from '@shared/types/api'

// The `quilt_core.js` module has no public type declarations for the
// new history functions yet (the WASM pkg is built from Rust). We
// declare them here so call sites stay type-safe. The runtime values
// come from the same JS module.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const pkg = (initWasmRaw as any).__wasm ?? (initWasmRaw as any)

// ── Lifecycle ─────────────────────────────────────────────────────

/** Initialise the WASM module. Safe to call multiple times. */
export async function loadWasm(): Promise<void> {
  await initWasmRaw()
  initPanicHook()
  if (!ping()) throw new Error('quilt-core WASM ping returned false')
}

export { get_version, ping }

// ── Page state ────────────────────────────────────────────────────

/** Load blocks for a page and stash them in the WASM-side BLOCKS map. */
export function wasmLoadPage(pageId: string, blocks: Block[]): unknown {
  return load_page(pageId, JSON.stringify(blocks))
}

/** Get the WASM-side state snapshot for a page. */
export function wasmGetState(pageId: string): unknown {
  const raw = get_state(pageId)
  return typeof raw === 'string' ? JSON.parse(raw) : raw
}

/** Dispatch a `types::OutlinerCommand` (the WASM boundary, not the history one). */
export function wasmDispatch(pageId: string, command: unknown): unknown {
  const raw = dispatch(
    pageId,
    typeof command === 'string' ? command : JSON.stringify(command),
  )
  return typeof raw === 'string' ? JSON.parse(raw) : raw
}

/** Parse inline content into typed segments. */
export function wasmParseInline(content: string): unknown {
  const raw = parse_inline(content)
  return typeof raw === 'string' ? JSON.parse(raw) : raw
}

// ── History-stack bridge ──────────────────────────────────────────
//
// The functions below come from the Rust `HistoryStack` bridge
// (`crates/quilt-core/src/wasm.rs`). They are intentionally typed as
// `(...args: unknown[]) => unknown` because the pkg's .d.ts is
// regenerated by `wasm-pack build` and the build artefact is not
// re-built on every TypeScript change. The wrappers below translate
// between TypeScript and the pkg's expected call shape.

type WasmExport = (...args: unknown[]) => unknown

// We pull the functions off the module object the same way the
// generated JS would, by name. The pkg's `__wbindgen_export_*` is
// private, so we use a safe fallback: if the named export exists, use
// it; otherwise the function throws at runtime.
function getExport(name: string): WasmExport | undefined {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const mod = (initWasmRaw as any)
  if (typeof mod === 'function') {
    // The default export in some versions is the module itself
    if (name in mod) return mod[name].bind(mod)
  }
  // Named exports are static — try to resolve them at module load.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const all = mod as Record<string, unknown>
  if (name in all) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const fn = (all as any)[name]
    return typeof fn === 'function' ? (fn as WasmExport) : undefined
  }
  return undefined
}

// Throws a clear error if the WASM pkg was not rebuilt with the new
// history exports. After `wasm-pack build`, the imports at the top
// of this file should be extended and these shims can be replaced
// with direct imports.
function requireExport(name: string): WasmExport {
  // Preferred path: the named import from `./pkg/quilt_core.js`.
  // If `wasm-pack build` has been run, the imports above are
  // extended and `pkg[name]` resolves.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const direct = (pkg as any)?.[name]
  if (typeof direct === 'function') return direct as WasmExport
  // Fallback: scan the whole module.
  const fallback = getExport(name)
  if (fallback) return fallback
  throw new Error(
    `WASM export "${name}" not found. Run \`wasm-pack build\` in ` +
      `crates/quilt-core to regenerate pkg/quilt_core.js.`,
  )
}

/** Initialise a history stack. Returns a `u32` id. */
export function wasmHistoryNew(blocks: Block[]): number {
  return requireExport('history_new')(blocks) as number
}

/** Apply a command and return the new block list. */
export function wasmHistoryApply(
  stackId: number,
  command: OutlinerCommand,
): Block[] {
  return requireExport('history_apply')(stackId, command) as Block[]
}

/** Undo the last command. Returns the new block list, or `null`. */
export function wasmHistoryUndo(stackId: number): Block[] | null {
  const out = requireExport('history_undo')(stackId)
  return out == null ? null : (out as Block[])
}

/** Redo the next command. Returns the new block list, or `null`. */
export function wasmHistoryRedo(stackId: number): Block[] | null {
  const out = requireExport('history_redo')(stackId)
  return out == null ? null : (out as Block[])
}

export function wasmHistoryCanUndo(stackId: number): boolean {
  return Boolean(requireExport('history_can_undo')(stackId))
}

export function wasmHistoryCanRedo(stackId: number): boolean {
  return Boolean(requireExport('history_can_redo')(stackId))
}

export function wasmHistoryFree(stackId: number): void {
  requireExport('history_free')(stackId)
}

// ── Re-exports for the legacy page-level undo/redo (now no-ops) ───

export const wasmUndo = undo
export const wasmRedo = redo

// Suppress the "unused variable" warning for the `pkg` reference while
// it remains the primary route into the module. Once the imports at
// the top of this file are extended, the line can be removed.
void pkg
